### ISSUE TITLE
Use conventional commits

### ISSUE THREAD

**Issue by krishguptadev** [avneesh0612/voyagger#21]
Usage of conventional commits would be relatively better.

**Comment by AnishDe12020** [comment]
Can I take this one up? (i can also add eslint, the eslint ci and a commitlint ci)

**Comment by krishguptadev** [comment]
Sure! @avneesh0612 can you assign them the issues. (https://github.com/avneesh0612/voyagger/issues/19, https://github.com/avneesh0612/voyagger/issues/20 and https://github.com/avneesh0612/voyagger/issues/21). I'll do #22

**Comment by AnishDe12020** [comment]
> Sure! @avneesh0612 can you assign them the issues. (#19, #20 and #21). I'll do #22

Ok, I will setup prettier, eslint, pre-commit hooks for the same, eslint workflow, commitlint and commitlint workflow and then you can do the changelog

**Comment by avneesh0612** [comment]
Sure, I sill assign them
